# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0013_auto_20170101_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='options_obuv',
            name='brend',
        ),
        migrations.RemoveField(
            model_name='options_obuv',
            name='name',
        ),
        migrations.RemoveField(
            model_name='options_obuv',
            name='size',
        ),
        migrations.RemoveField(
            model_name='options_obuv',
            name='type',
        ),
        migrations.DeleteModel(
            name='BrendObuv',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Options_obuv',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='TypeObuv',
        ),
    ]
