# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0015_auto_20170101_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options_obuv',
            new_name='OptionsObuv',
        ),
    ]
