# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0016_auto_20170101_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='optionsobuv',
            name='brend',
        ),
        migrations.RemoveField(
            model_name='optionsobuv',
            name='item',
        ),
        migrations.RemoveField(
            model_name='optionsobuv',
            name='size',
        ),
        migrations.RemoveField(
            model_name='optionsobuv',
            name='type',
        ),
        migrations.DeleteModel(
            name='BrendObuv',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='OptionsObuv',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='TypeObuv',
        ),
    ]
