# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0018_auto_20170101_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_obuv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.Item')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.Size')),
            ],
        ),
        migrations.RemoveField(
            model_name='optionsobuv',
            name='number',
        ),
        migrations.RemoveField(
            model_name='optionsobuv',
            name='size',
        ),
    ]
