# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0019_auto_20170115_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store_obuv',
            new_name='StoreObuv',
        ),
    ]
