# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0021_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=1, verbose_name='Количетсво товара')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.Order'),
        ),
    ]
