# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0022_auto_20170119_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Order_params',
        ),
    ]
