# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0023_auto_20170119_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, verbose_name='Ссылка на картинку')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет фона')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на каталог с параметрами')),
            ],
        ),
    ]
