# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0025_numberviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrendSumki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Бренд сумок')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsSumki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.BrendSumki')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.Item')),
            ],
        ),
        migrations.CreateModel(
            name='TypeSumki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип сумки')),
            ],
        ),
        migrations.AddField(
            model_name='optionssumki',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.TypeSumki'),
        ),
    ]
