# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0026_auto_20170204_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Общее количество товара'),
        ),
    ]
