# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0027_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sales',
            field=models.SmallIntegerField(default=0, verbose_name='Продан или нет товар'),
        ),
    ]
