# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0028_item_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_opt_obuv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='optionsobuv',
            name='sizes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sumki_online.StoreObuv'),
        ),
        migrations.AddField(
            model_name='order_opt_obuv',
            name='item_opt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.OptionsObuv'),
        ),
        migrations.AddField(
            model_name='order_opt_obuv',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.Order_params'),
        ),
    ]
