# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0029_auto_20170308_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeobuv',
            name='number',
            field=models.SmallIntegerField(verbose_name='Количествоо'),
        ),
    ]
