# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0030_auto_20170308_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionsobuv',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='storeobuv',
            name='number',
            field=models.SmallIntegerField(default=1, verbose_name='Количествоо'),
        ),
    ]
