# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0031_auto_20170311_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_opt_obuv',
            name='item_opt',
        ),
        migrations.RemoveField(
            model_name='order_opt_obuv',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order_opt_obuv',
        ),
    ]
