# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0033_order_size_obuv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_size_obuv',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_size_obuv',
            name='size',
        ),
        migrations.DeleteModel(
            name='Order_size_obuv',
        ),
    ]
