# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumki_online', '0036_auto_20170312_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_size_obuv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumki_online.Order_params')),
                ('size', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sumki_online.Size')),
            ],
        ),
    ]
